const meetups = [
  {
    id: 1,
    createdOn: Date.now(),
    topic: 'Andela Learning Community 2.0',
    location: 'University of Rwanda / College of Science and Technology',
    happeningOn: Date.now(),
    images: 'sample1.png',
    Tags: ['Andela', 'ALC', 'Learning'],
  },
  {
    id: 2,
    createdOn: Date.now(),
    topic: 'Andela Learning Community 3.0',
    location: 'Convention Centre',
    happeningOn: Date.now(),
    images: 'sample2.png',
    Tags: ['Convention', 'ALC', 'Andela'],
  },
  {
    id: 3,
    createdOn: Date.now(),
    topic: 'Andela Learning Community 4.0',
    location: 'Radisson Blu Hotel',
    happeningOn: '10/22/2019',
    images: 'sample3.png',
    Tags: ['Andela', 'ALC', 'Learning'],
  },
  {
    id: 4,
    createdOn: Date.now(),
    topic: 'Andela Learning Community 5.0',
    location: 'Convention Centre',
    happeningOn: '10/22/2020',
    images: 'sample4.png',
    Tags: ['Convention', 'ALC', 'Andela'],
  },
  {
    id: 5,
    createdOn: Date.now(),
    topic: 'Andela Learning Community 6.0',
    location: 'Telecom House',
    happeningOn: '10/22/2021',
    images: 'sample5.png',
    Tags: ['Andela', 'ALC', 'Learning'],
  },
  {
    id: 6,
    createdOn: Date.now(),
    topic: 'Andela Learning Community 7.0',
    location: 'KIST',
    happeningOn: '10/22/2022',
    images: 'sample6.png',
    Tags: ['Convention', 'ALC', 'Andela'],
  },
];
module.exports = meetups;
